services:
  mysql:
    image: mysql:8
    container_name: FinanceTracker_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: FinanceTracker
      MYSQL_USER: myuser
      MYSQL_PASSWORD: MyPass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - finance_tracker_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "myuser", "-pMyPass123"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - finance_tracker_network

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: FinanceTracker
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - finance_tracker_network

volumes:
  mysql_data:
  redis_data:
  mongodb_data:

networks:
  finance_tracker_network:
    driver: bridge