[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/backend/*"
  to = "https://finance-tracker-backend-iwct.onrender.com/:splat"
  status = 200
  force = true
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
